Remove one instance of event_module.del()
It appears that this is not required, at least when implemented based
on kqueue() as in FreeBSD.

These calls caused error messages in the log file:

kqueue.c:210: error: kevent() error 9 on 2391 filter:-1 flags:0x4000

I have not tried to understand the full event notification life-cycle,
and these calls may be needed for other notification methods than
kqueue, but at least on FreeBSD they seem to be wrong.