Do not remove kevent from closed request sockwt.
After a successful transfer pass EV_FLAG_CLOSING to the kevent delete
function since the corresponding socket has been been closed and there
is no kevent request record to delete.

This prevents spurious error messages:

    kqueue.c:210: error: kevent() error 9 on 2391 filter:-1 flags:0x4000